server:
  port: ${port:8762}

spring:
  application:
    name: eurekaServer2

eureka:
  instance:
    hostname: eurekaServer2
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://eurekaServer1:8761/eureka/}
