server:
  port: ${port:8761}

spring:
  application:
    name: eurekaServer1

eureka:
  instance:
    hostname: ${hostname:eurekaServer1}
  client: 
    serviceUrl: 
      defaultZone: ${eureka.serviceUrl:http://eurekaServer2:8762/eureka/}
